version: "3.9"

services:
  vanillajs:
    container_name: vanillajs
    build: ./build
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../../.env
      - .env
    volumes:
      - .:/app