version: "3.9"

services:
  front:
    build: ./build
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ../../.env
      - .env
    command: ["browser-sync", "start", "--server", "build", "--port", "${PORT}", "--no-open", "--host", "0.0.0.0", "--no-ui"]
    volumes:
      - ./build:/app/build