version: "3.8"
services:
  vanillajs:
    container_name: vanillajs
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html:ro
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
